name = "origen-chat"
compatibility_date = "2025-04-10"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "origen-chat-db"
database_id = "1262c9af-0a6d-4baa-93b8-9cf87aec1c45"

[vars]
APP_URL = "https://origen-chat.moikapy.workers.dev"