#!/bin/bash
# Fix duplicate exports in next-env.mjs generated by OpenNext
FILE=".open-next/cloudflare/next-env.mjs"
if [ -f "$FILE" ]; then
  # Remove duplicate lines (keep only first occurrence of each export)
  awk '!seen[$0]++' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
  echo "Fixed $FILE"
fi
